# Generated by Django 6.0.2 on 2026-03-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='is_removed_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
