# Generated by Django 6.0.2 on 2026-04-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_approval_status_job_is_removed_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
