# Generated by Django 6.0.2 on 2026-04-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='auto_reject',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='auto_shortlist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reject_threshold',
            field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name='job',
            name='shortlist_threshold',
            field=models.FloatField(default=70),
        ),
    ]
