# Generated by Django 6.0.2 on 2026-04-11 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_auto_reject_job_auto_shortlist_and_more'),
        ('users', '0007_candidateprofile_highest_education'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['approval_status'], name='jobs_job_approva_672827_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employer'], name='jobs_job_employe_da1c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='jobs_job_created_1b3a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_featured'], name='jobs_job_is_feat_3f31c0_idx'),
        ),
        migrations.AddIndex(
            model_name='savedjob',
            index=models.Index(fields=['candidate'], name='jobs_savedj_candida_3c4d62_idx'),
        ),
    ]
