# Generated by Django 6.0.2 on 2026-04-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_jobs_job_status_7d017a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
    ]
