# Generated by Django 6.0.2 on 2026-03-02 06:11

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=apps.users.models.resume_upload_path),
        ),
    ]
