# Generated by Django 6.0.2 on 2026-03-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_candidateprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
