# Generated by Django 6.0.2 on 2026-03-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_candidateprofile_location'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['location'], name='users_candi_locatio_d1946f_idx'),
        ),
    ]
