# Generated by Django 6.0.2 on 2026-03-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_candidateprofile_users_candi_locatio_d1946f_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='is_verified',
            new_name='is_approved',
        ),
    ]
