# Generated by Django 6.0.2 on 2026-04-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_flag_count_user_is_flagged_adminactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='highest_education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
