# Generated by Django 6.0.2 on 2026-04-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_candidateprofile_highest_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
