# Generated by Django 6.0.2 on 2026-04-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_candidateprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior')], max_length=30, null=True),
        ),
    ]
