# Generated by Django 6.0.2 on 2026-04-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ats_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
    ]
