# Generated by Django 6.0.2 on 2026-04-11 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_jobapplication_ats_score_and_more'),
        ('jobs', '0009_job_auto_reject_job_auto_shortlist_and_more'),
        ('users', '0007_candidateprofile_highest_education'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='applicationstatuslog',
            index=models.Index(fields=['application'], name='application_applica_3a067b_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatuslog',
            index=models.Index(fields=['changed_at'], name='application_changed_4a5841_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='application_job_id_f7a30b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['candidate'], name='application_candida_670028_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applied_date'], name='application_applied_2a8d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['ats_score'], name='application_ats_sco_f9a829_idx'),
        ),
    ]
