# Generated by Django 6.0.2 on 2026-05-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_applicationstatuslog_application_applica_3a067b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_call_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ai_call_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ai_call_status',
            field=models.CharField(choices=[('not_triggered', 'Not Triggered'), ('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_triggered', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ai_retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
